# Generated by Django 5.1.4 on 2025-05-05 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(null=True)),
                ('response', models.CharField(null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
