# Generated by Django 5.1.4 on 2025-05-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_chatlogs_user_chatsession_chatlogs_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10, null=True),
        ),
    ]
