# Generated by Django 5.1.4 on 2025-05-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_chatsession_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='status',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
