# Generated by Django 5.1.4 on 2025-05-22 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_chatsession_status_chatsession_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
