# Generated by Django 5.1.4 on 2025-06-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlogs',
            name='score',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
