# Generated by Django 5.1.4 on 2025-06-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_chatlogs_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlogs',
            name='emosi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
